import type { Metadata } from "next";
import WalletProvider from "@/components/WalletProvider";
import { GoogleOAuthProviderWrapper } from "@/components/GoogleOAuthProvider";
import "./globals.css";
import { ToastContainer } from 'react-toastify';
import { Inter } from 'next/font/google';

import localFont from 'next/font/local'
import WelcomeSlideshow from "@/components/onboarding/WelcomeSlideshow";
import HeaderAd from "@/components/HeaderAd";
import NavBar from "@/components/NavBar";
import MarketTrends from "@/components/MarketTrends";
import TokenSwapCard from "@/components/TokenSwapCard";
import { Dialog } from "@/components/ui/dialog";
import { ErrorBoundary } from "@/components/ErrorBoundary";

const grotesqueArabicPro = localFont({
  src: './fonts/BasisGrotesqueArabicPro-Regular.woff2',
  display: 'swap',
});

const inter = Inter({
  subsets: ['latin'], // Specify the necessary subsets
  display: 'swap',    // Optional: Controls how font is displayed while loading
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} ${grotesqueArabicPro.className} antialiased`}>
        <ErrorBoundary>
          <GoogleOAuthProviderWrapper>
            <Dialog>
              <WalletProvider>
                <HeaderAd />
                <NavBar />
                <MarketTrends />
                {children}
                <WelcomeSlideshow />
                <div className="fixed bottom-15 right-20 z-50">
                  <TokenSwapCard />
                </div>
              </WalletProvider>
            </Dialog>
          </GoogleOAuthProviderWrapper>
        </ErrorBoundary>
        <ToastContainer
          position="top-right"
          autoClose={3000}
          hideProgressBar={false}
          newestOnTop={false}
          closeOnClick
          rtl={false}
          pauseOnFocusLoss
          draggable
          pauseOnHover
          theme="dark"
        />
      </body>
    </html>
  );
}
